Proiect/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Proiect.Data;
using Proiect.Models;
using System.Data;

namespace Proiect.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext db;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;
        public CategoriesController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            var categories = from Category in db.Categories
                             orderby Category.CategoryName
                             select Category;
            ViewBag.Categories = categories;

            return View();
        }

        public ActionResult Show(int id)
        {
            Category? category = db.Categories.Find(id);

            if (category == null)
                return RedirectToAction("Index");

            return View(category);
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(Category cat)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(cat);
                db.SaveChanges();

                TempData["message"] = "Categoria a fost adaugata";

                return RedirectToAction("Index");
            }

            return View(cat);
        }

        public ActionResult Edit(int id)
        {
            Category? category = db.Categories.Find(id);

            if (category == null)
                return RedirectToAction("Index");

            return View(category);
        }

        [HttpPost]
        public ActionResult Edit(int id, Category requestCategory)
        {
            Category category = db.Categories.Find(id);

            if (ModelState.IsValid)
            {
                category.CategoryName = requestCategory.CategoryName;
                db.SaveChanges();

                TempData["message"] = "Categoria a fost modificata!";

                return RedirectToAction("Index");
            }

            return View(requestCategory);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Category category = db.Categories.Find(id);

            db.Categories.Remove(category);
            db.SaveChanges();

            TempData["message"] = "Categoria a fost stearsa";

            return RedirectToAction("Index");
        }

    }
}

Proiect/Controllers/GroupsController.cs
using Proiect.Data;
using Proiect.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Collections.Generic;
using Ganss.Xss;

namespace Proiect.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        private readonly ApplicationDbContext db;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;
        public GroupsController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        //  Functii ajutatoare
        [NonAction]
        public IEnumerable<SelectListItem> GetAllCategories()
        {
            // generam o lista de tipul SelectListItem fara elemente
            var selectList = new List<SelectListItem>();

            // extragem toate categoriile din baza de date
            var categories = from cat in db.Categories
                             select cat;

            // iteram prin categorii
            foreach (var category in categories)
            {
                // adaugam in lista elementele necesare pentru dropdown
                // id-ul categoriei si denumirea acesteia
                selectList.Add(new SelectListItem
                {
                    Value = category.Id.ToString(),
                    Text = category.CategoryName.ToString()
                });
            }

            return selectList;
        }

        [NonAction]
        public UserGroup? GetUserGroup(int groupId, string userId)
        {
            UserGroup? userGroup = db.UserGroups.Where(ug => ug.GroupId == groupId)
                                                .Where(ug => ug.UserId == userId)
                                                .FirstOrDefault();

            return userGroup;
        }

        [NonAction]
        private void SetAccessRights(int id)
        {
            var curentUser = _userManager.GetUserId(User);

            ViewBag.curentUser = curentUser;
            ViewBag.userGroup = GetUserGroup(id, curentUser);
            ViewBag.isAdmin = User.IsInRole("Admin");
        }

        //  Partea de CRUD
        public IActionResult Index()
        {
            var groups = db.Groups.Include("Category");

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }

            // Alegem sa afisam 3 grupuri pe pagina
            int _perPage = 3;
            int totalItems = groups.Count();

            // Se preia pagina curenta din View-ul asociat
            // Numarul paginii este valoarea parametrului page din ruta
            // /Groups/Index?page=valoare
            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);
            // Pentru prima pagina offsetul o sa fie zero
            // Pentru pagina 2 o sa fie 3
            // Asadar offsetul este egal cu numarul de grupuri care au fost deja afisate pe paginile anterioare
            var offset = 0;
            // Se calculeaza offsetul in functie de numarul paginii la care suntem
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            // Se preiau articolele corespunzatoare pentru fiecare pagina la care ne aflam
            // in functie de offset
            var paginatedGroups = groups.Skip(offset).Take(_perPage);
            // Preluam numarul ultimei pagini
            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);
            // Trimitem grupurile cu ajutorul unui ViewBag catre View-ul corespunzator

            ViewBag.Groups = paginatedGroups;

            return View();
        }

        public IActionResult Show(int id)
        {
            Group? group = db.Groups.Include("Category")
                                    .Include("Messages")
                                    .Include("Messages.User")
                                    .Where(grp => grp.Id == id)
                                    .FirstOrDefault();

            if (group == null)
                return RedirectToAction("Index");

            SetAccessRights(id);

            return View(group);
        }

        [HttpPost]
        public IActionResult Show([FromForm] Message message)
        {
            message.Date = DateTime.Now;
            message.UserId = _userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                db.Messages.Add(message);
                db.SaveChanges();

                return RedirectToAction("Show", message.GroupId);
            }

            Group group = db.Groups.Include("Category")
                                   .Include("Messages")
                                   .Include("Messages.User")
                                   .Where(grp => grp.Id == message.GroupId)
                                   .First();

            SetAccessRights((int)message.GroupId);

            return View(group);
        }

        public IActionResult New()
        {
            Group group = new Group();
            
            group.AllCategories = GetAllCategories();

            return View(group);
        }

        [HttpPost]
        public IActionResult New(Group group)
        {
            var sanitizer = new HtmlSanitizer();
            group.Date = DateTime.Now;
            UserGroup ug = new UserGroup();
            
            if (ModelState.IsValid)
            {
                group.Description = sanitizer.Sanitize(group.Description);
                db.Groups.Add(group);
                db.SaveChanges();

                ug.UserId = _userManager.GetUserId(User);
                ug.GroupId = group.Id;
                ug.IsModerator = true;
                ug.IsAccepted = true;
                db.UserGroups.Add(ug);
                db.SaveChanges();

                TempData["message"] = "Grupul a fost adaugat";

                return RedirectToAction("Index");
            }

            group.AllCategories = GetAllCategories();

            return View(group);
        }

        public IActionResult Edit(int id)
        {
            Group? group = db.Groups.Include("Category")
                                    .Include("Messages")
                                    .Include("Messages.User")
                                    .Where(grp => grp.Id == id)
                                    .FirstOrDefault();

            if (group == null)
                return RedirectToAction("Index");

            UserGroup? userGroup = GetUserGroup(id, _userManager.GetUserId(User));

            if ((userGroup != null && userGroup.IsModerator) || User.IsInRole("Admin"))
            {
                if (group == null)
                    return RedirectToAction("Index");

                group.AllCategories = GetAllCategories();

                return View(group);
            }

            TempData["message"] = "Nu aveti dreptul de a edita acest grup!";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(int id, Group requestGroup)
        {
            var sanitizer = new HtmlSanitizer();
            Group group = db.Groups.Where(grp => grp.Id == id)
                                   .First();

            if (ModelState.IsValid)
            {
                requestGroup.Description=sanitizer.Sanitize(requestGroup.Description);
                group.Name = requestGroup.Name;
                group.Description = requestGroup.Description;
                group.CategoryId = requestGroup.CategoryId;
                db.SaveChanges();

                TempData["message"] = "Grupul a fost modificat!";

                return RedirectToAction("Index");
            }

            requestGroup.AllCategories = GetAllCategories();

            return View(requestGroup);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            UserGroup userGroup = GetUserGroup(id, _userManager.GetUserId(User));

            if ((userGroup != null && userGroup.IsModerator) || User.IsInRole("Admin"))
            {

                Group group = db.Groups.Include("Messages")
                                       .Where(grp => grp.Id == id)
                                       .First();

                db.Groups.Remove(group);
                db.SaveChanges();

                TempData["message"] = "Grupul a fost sters";
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul de a sterge acest grup!";
            }
            
            return RedirectToAction("Index");
        }

        public IActionResult ShowMembers(int id)
        {
            Group? group = db.Groups.Where(grp => grp.Id == id)
                                    .FirstOrDefault();

            if (group == null)
                return RedirectToAction("Index");

            var users = db.UserGroups.Include("User")
                                     .Where(ug => ug.GroupId == id);
            ViewBag.users = users;

            SetAccessRights(id);

            return View();
        }

        [HttpPost]
        public IActionResult Join(int id)
        {
            var curentUser = _userManager.GetUserId(User);

            //  verific daca userul face deja parte din grupul
            //  in care vrea sa dea join
            UserGroup? ug = GetUserGroup(id, curentUser);

            if (ug == null)
            {
                ug = new UserGroup();
                ug.UserId = curentUser;
                ug.GroupId = id;

Proiect/Views/Shared/GroupInfo.cshtml
<div class="card-body">

    <h3 class="card-title py-3 px-3 ">@Model.Name</h3>

    <div class="card-text bg-light text-dark">@Model.Description</div>

    <div class="d-flex justify-content-between flex-row mt-5">

        <div><i class="bi bi-globe"></i> @Model.Category.CategoryName</div>

        <span >@Model.Date</span>

    </div>

</div>

Proiect/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proiect</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proiect.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css">

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style1.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="style1.css" />

</head> 
<body>
    <header class="position-absolute  start-0  end-0">
        <div class="container-fluid">
            <div class="row">
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-brown box-shadow ">
                        <div class="container-fluid">
                            <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">University Rooms</a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    

                                    @if (User.IsInRole("Admin"))
                                    {
                                        
                                        
                                        <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                                        </li>
                                        <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Groups" asp-action="Index">Groups</a>
                                        </li>
                                        <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Groups" asp-action="New">Adauga grup</a>
                                        </li>
                                        <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Groups" asp-action="ShowMy">My groups</a>
                                        </li>
                                        
                                    }
                                    @if (User.IsInRole("User"))
                                    {
                                        
                                 
                                        <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Groups" asp-action="Index">Groups</a>
                                        </li>
                                        <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Groups" asp-action="New">Adauga grup</a>
                                        </li>
                                        <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Groups" asp-action="ShowMy">My groups</a>
                                        </li>
                                        
                                    }
                                </ul>
                            <partial name="_LoginPartial" />
                            </div>
                        </div>
                    </nav>
                
                
            </div>
        </div>
    </header>

    <div class="wallpaperIndex vh-100">
            <main role="main" class="pb-3 pt-5">
            @RenderBody() 
            </main>
        </div>
    

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    
   

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Summernote.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>